gText_NurseIntro_Morning::
	.string "Good morning!\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "Would you like to rest your POKéMON?$"

gText_NurseIntro_Day::
	.string "Good day!\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "Would you like to rest your POKéMON?$"

gText_NurseIntro_Evening::
	.string "Good evening!\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "Would you like to rest your POKéMON?$"

gText_NurseIntro_Night::
	.string "Good evening! You're out late.\n"
	.string "Welcome to our POKéMON CENTER.\p"
	.string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"

gText_PleaseMakeUseOf::
	.string "Please make use of our services\n"
	.string "again anytime!$"

gText_PlsComeAgain::
	.string "Please come again!$"

gText_TakeCareStaySafeOutThere::
	.string "Take care and stay safe out there!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual_Morning::
	.string "I hope you're having\n"
	.string "a great morning, {PLAYER}!\p"
	.string "You want the usual, am I right?$"

gText_YouWantTheUsual_Day::
	.string "I hope you're having\n"
	.string "a great day, {PLAYER}!\p"
	.string "You want the usual, am I right?$"

gText_YouWantTheUsual_Evening::
	.string "I hope you're having\n"
	.string "a great evening, {PLAYER}!\p"
	.string "You want the usual, am I right?$"

gText_YouWantTheUsual_Night::
	.string "How's your night going, {PLAYER}?\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_TakeCareStaySafeOutTherePlayer::
	.string "Take care and stay safe out there,\n"
	.string "{PLAYER}!$"
